---
verifier:
  name: inspec

driver:
  name: vagrant
  network:
    - [ "forwarded_port", { guest: 8980, host: 8980, auto_correct: true } ]
    - [ "forwarded_port", { guest: 3000, host: 3000, auto_correct: false } ]
    - [ "forwarded_port", { guest: 9200, host: 9200, auto_correct: false } ]
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  product_version: 14.13.11
  require_chef_omnibus: 14.13.11

platforms:
  - name: centos-6.9
    attributes:
      opennms:
        templates: false
        conf:
          start_timeout: 50
        stable: true
        plugin:
          xml: true
          nsclient: true
  - name: centos-7
    attributes:
      opennms:
        templates: false
        conf:
          start_timeout: 50
        stable: true
        plugin:
          xml: true
          nsclient: true
suites:
  - name: templates_26
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[oracle_java8::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::webopts]
    attributes:
      opennms:
        version: 26.2.2-1
        templates: true
    verifier:
      inspec_tests:
        - path: test/integration/default
  - name: templates_27
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[oracle_java8::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::webopts]
    attributes:
      opennms:
        version: 27.2.0-1
        templates: true
    verifier:
      inspec_tests:
        - path: test/integration/default
